services:
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./indexer
    depends_on:
      - redis
    environment:
      - REDIS_ADDRESS=redis:6379
      - ETH_NODE_URL=http://172.17.0.1:8545
      - START_BLOCK_NUMBER=20949000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_network

  price_indexer:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./price_indexer
    depends_on:
      - redis
    environment:
      - REDIS_ADDRESS=redis:6379
      - CRYPTOCOMPARE_API_KEY=${CRYPTOCOMPARE_API_KEY}
    networks:
      - app_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./api
    ports:
      - "8080:9000"
    depends_on:
      - redis
    environment:
      - REDIS_ADDRESS=redis:6379
    networks:
      - app_network

volumes:
  redis_data:

networks:
  app_network:
    driver: bridge